
            # This is and autogenerated test case using PyUDS Test Builder v0.1 #
#Modified by: Mauricio Perea        Date: 30-Sep-20

from framework.shared_functions import device_under_test        
from Testcases.TestClass import TestCase
from inspect import stack as info
import unittest

test = TestCase()
class PyUDS_TestCase(unittest.TestCase):

    #== Positive Flow Read Multiple DID and Functional Messaging Tests ==#
    @classmethod
    def setUpClass(self):
        #== Initialize test case ==#
        test.begin(
            test_info=info(),
            writeTestResults=True,
            excel_tab='0x22'
        )

    @classmethod
    def tearDownClass(self):
        #== End Test Case ==#
        test.end()

    def test_001(self, name='Transition Server to defaultSession'):
        test.preconditions(
            step_info=info()          
        )

        test.step(
            step_title=name,
            start_tester_present=True,
            custom='10 01',
            expected={
                'response': 'Positive'
            }
        )

    def test_002(self, name='requestOutOfRange - UnsupportedDID'):

        test.preconditions(
            step_info=info(),
            functionalAddr=True
        )
        test.step(
            step_title=name,
            custom='22 44 58',

            expected={
                'response'   : 'No response'
            }
        )