
            # This is and autogenerated test case using PyUDS Test Builder v0.3 #
        
from framework.shared_libs.transport_layer import TransportLayer
from framework.shared_functions import tools, LogsPath
from Testcases.TestClass import TestCase
from inspect import stack as info
import unittest, time

test = TestCase()
class PyUDS_TestCase(unittest.TestCase):

    #== PyUDS - Autogenerated Test Case Template ==#
    @classmethod
    def setUpClass(self):
        #== Initialize test case ==#
        test.begin(
            test_info=info(),
            writeTestResults=True,
            excel_tab='Transport Layer'
        )
        self.TransportLayer = TransportLayer(LogsPath+'\\TraceLog.asc')
        
    @classmethod
    def tearDownClass(self):
        #== End Test Case ==#
        test.end()

    def test_001(self, name='Transport Layer 27'):

        # *CHECKED* - Check-box
        test.canoe.set_envVariable(TransportLayer27=1)

        # *PUSH* - Run selected test cases
        test.canoe.set_envVariable(RunTransportLayerTC=1)
        time.sleep(0.75)
        test.canoe.set_envVariable(RunTransportLayerTC=0)
        test.canoe.set_envVariable(TransportLayer27=0)

        # Wait for Transport Layer Test Case to be finished
        print('Please wait until TC is completed...')
        time.sleep(5)
        test.canoe.stop()
        analysis_results = self.TransportLayer.test_case_27()
        test.compare(analysis_results, True, 
                        step='test_001') 
        
        # -- Added to fill CG Report --
        test.compare(analysis_results, True,
                        step='test_002')
        # -- Added to fill CG Report --