
            # This is and autogenerated test case using PyUDS Test Builder v0.3 #
#Modified by: Mauricio Perea        Date: 5-Nov-20
        
from framework.shared_functions import tools, device_under_test
from Testcases.TestClass import TestCase
from inspect import stack as info
import unittest, time

test = TestCase()
class PyUDS_TestCase(unittest.TestCase):

    #== PyUDS - Autogenerated Test Case Template ==#
    @classmethod
    def setUpClass(self):
        #== Initialize test case ==#
        test.begin(
            test_info=info(),
            writeTestResults=True,
            excel_tab='0x31'
        )

    @classmethod
    def tearDownClass(self):
        #== End Test Case ==#
        test.end()


    def test_016(self, name='<Transition to extendedSession>'):
        test.preconditions(
            step_info=info(),
            mec_zero=True,
            sbat=False
        )
        test.step(
            step_title=name,
            custom='10 03',
            expected={
                'response': 'Positive',
                'dataLength': '4'
            }
        )

    def test_016_2(self, name='<Activate TesterPresent>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )

    def test_017(self, name='<Start Routine> Physical Address Req'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='31 01 02 1E',
            expected={
                'response': 'Negative',
                'data': '33'
            }
        )

    def test_018(self, name='<Unlock Security Level 01, ServiceProgramming>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            request_seed='01',
            expected={
                'response'            : 'Positive',
                'dataLength'          : 31,
                'unexpected_response' : True,
                'partialData'         : ('00', 'FF')
            }
        )

    def test_019(self, name='<Unlock the Server via security access 01 service>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            send_key='01',
            expected={
                'response': 'Positive'
            }
        )

    def test_020(self, name='<Verify Server is enforcing ECU Service Programming Routine>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='31 01 02 1E ',
            expected={
                'response': 'Positive'
            }
        )

    def test_021(self, name='Send valid testerPresent, service 3E, within P3 for 2 minutes + Stop periodically transmitted TesterPresent and wait for S3 Timeout + 100 msec, 5.1 seconds, for the Session Timing parameter to timeout'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )
        tools.timer.input('Wait for 2 minutes...', timeout=120)
        test.preconditions(current_step='- Stop tester present -')
        test.step(step_title='- Stop tester present -',
                    stop_tester_present=True)
        tools.timer.input('Wait for S3 Timeout + 100ms', timeout=6)


    def test_023(self, name='<Verify return to defaultSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='28 03 01',
            expected={
                'response': 'Negative',
                'data': '7F'
            }
        )

    def test_024(self, name='<Transition to extendedSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='10 03',
            expected={
                'response': 'Positive',
                'dataLength': '4'
            }
        )

    def test_025(self, name='<Activate TesterPresent>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )

    def test_027(self, name='<Start Routine> Physical Address Req'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='31 01 02 1E',
            expected={
                'response': 'Negative',
                'data': '33'
            }
        )

    def test_028(self, name='<Unlock Security Level 03, ServiceProgramming>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            request_seed='03',
            expected={
                'response'            : 'Positive',
                'dataLength'          : 31,
                'unexpected_response' : True,
                'partialData'         : ('00', 'FF')
            }
        )

    def test_029(self, name='<Unlock the Server via security access 03 service>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            send_key='03',
            expected={
                'response': 'Positive'
            }
        )

    def test_030(self, name='<Verify Server is enforcing ECU Service Programming Routine>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='31 01 02 1E',
            expected={
                'response': 'Positive'
            }
        )

    def test_031(self, name='Send valid testerPresent, service 3E, within P3 for 2 minutes + Stop periodically transmitted TesterPresent and wait for S3 Timeout + 100 msec, 5.1 seconds, for the Session Timing parameter to timeout'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )
        tools.timer.input('Wait for 2 minutes...', timeout=120)
        test.preconditions(current_step='- Stop tester present -')
        test.step(step_title='- Stop tester present -',
                    stop_tester_present=True)
        tools.timer.input('Wait for S3 Timeout + 100ms', timeout=6)

    def test_033(self, name='<Verify return to defaultSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='28 03 01',
            expected={
                'response': 'Negative',
                'data': '7F'
            }
        )

    def test_034(self, name='<Transition to extendedSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='10 03',
            expected={
                'response': 'Positive',
                'dataLength': '4'
            }
        )

    def test_035(self, name='<Activate TesterPresent>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )

    def test_037(self, name='<Start Routine> Physical Address Req'):
        if device_under_test is 'SCL':
            print('This test is not applicable for %s'%device_under_test)
            return 0
        test.preconditions(
            step_info=info()
        )
        if device_under_test is 'MSM':
            test.step(
                step_title=name,
                custom='31 01 02 7A 02',
                expected={
                    'response': 'Negative',
                    'data': '33'
                }
            )
        if device_under_test in ['ARB','TCP']:
            test.step(
                step_title=name,
                custom='31 01 02 C0 00',
                expected={
                    'response': 'Negative',
                    'data': '33'
                }
            )
        if device_under_test == 'PTM':
            test.step(
                step_title=name,
                custom='31 01 03 42 00 00',
                expected={
                    'response': 'Negative',
                    'data': '33'
                }
            )            
    def test_038(self, name='<Unlock Security Level 09, ServiceProgramming>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            request_seed='09',
            expected={
                'response'            : 'Positive',
                'dataLength'          : 31,
                'unexpected_response' : True,
                'partialData'         : ('00', 'FF')
            }
        )

    def test_039(self, name='<Unlock the Server via security access 09 service>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            send_key='09',
            expected={
                'response': 'Positive'
            }
        )

    def test_040(self, name='<Verify Server is enforcing ECU Service Programming Routine>'):
        test.preconditions(
            step_info=info()
        )
        if device_under_test is 'MSM':
            test.step(
                step_title=name,
                custom='31 01 02 7A 02',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test is 'SCL':
            test.step(
                step_title=name,
                custom='31 01 FF 01',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test in ['ARB','TCP']:
            test.step(
                step_title=name,
                custom='31 01 02 C0 00',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test == 'PTM':
            test.preconditions(
                step_info=info(),
                signal=['RCIP_RrClsrMtnCtlParmEnblAuth','SrlDat2_Prtctd_PDU',1]                
                ) 
            time.sleep(5)           
            test.step(
                step_title=name,
                custom='31 01 03 42 00 00',
                expected={
                    'response': 'Positive'
                }
            )

    def test_041(self, name='Send valid testerPresent, service 3E, within P3 for 2 minutes + Stop periodically transmitted TesterPresent and wait for S3 Timeout + 100 msec, 5.1 seconds, for the Session Timing parameter to timeout'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )
        tools.timer.input('Wait for 2 minutes...', timeout=120)
        test.preconditions(current_step='- Stop tester present -')
        test.step(step_title='- Stop tester present -',
                    stop_tester_present=True)
        tools.timer.input('Wait for S3 Timeout + 100ms', timeout=6)

    def test_043(self, name='<Verify return to defaultSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='28 03 01',
            expected={
                'response': 'Negative',
                'data': '7F'
            }
        )

    def test_044(self, name='<Transition to extendedSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='10 03',
            expected={
                'response': 'Positive',
                'dataLength': '4'
            }
        )

    def test_045(self, name='<Activate TesterPresent>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )

    def test_047(self, name='<Start Routine> Physical Address Req'):
        if device_under_test in ['SCL','MSM']:
            print(name, 'Test is not applicable for %s'%device_under_test)
            return 0
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='31 01 04 1A', #no suitable RID for MSM and PTM
            expected={
                'response': 'Negative',
                'data': '33'
            }
        )

    def test_048(self, name='<Unlock Security Level 0B, ServiceProgramming>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            request_seed='0B',
            expected={
                'response'            : 'Positive',
                'dataLength'          : 31,
                'unexpected_response' : True,
                'partialData'         : ('00', 'FF')
            }
        )

    def test_049(self, name='<Unlock the Server via security access 0B service>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            send_key='0B',
            expected={
                'response': 'Positive'
            }
        )

    def test_050(self, name='<Verify Server is enforcing ECU Service Programming Routine>'):
        test.preconditions(
            step_info=info()
        )
        if device_under_test is 'MSM':
            print(name, 'Test is not applicable for %s'%device_under_test)
            return 0
            test.step(
                step_title=name,
                custom='31 01 04 1A', #no suitable RID for MSM and PTM
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test is 'SCL':
            test.step(
                step_title=name,
                custom='31 01 FF 01',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test == 'TCP':
            test.step(
                step_title=name,
                custom='31 01 02 C0 00',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test in ['PTM','ARB']:
            print(name, 'Test is not applicable for %s'%device_under_test)
            return 0
            test.step(
                step_title=name,
                custom='NOT APLICABLE', #no suitable RID for MSM and PTM
                expected={
                    'response': 'Positive'
                }
            )
    def test_051(self, name='Send valid testerPresent, service 3E, within P3 for 2 minutes + Stop periodically transmitted TesterPresent and wait for S3 Timeout + 100 msec, 5.1 seconds, for the Session Timing parameter to timeout'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )
        tools.timer.input('Wait for 2 minutes...', timeout=120)
        test.preconditions(current_step='- Stop tester present -')
        test.step(step_title='- Stop tester present -',
                    stop_tester_present=True)
        tools.timer.input('Wait for S3 Timeout + 100ms', timeout=6)

    def test_053(self, name='<Verify return to defaultSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='28 03 01',
            expected={
                'response': 'Negative',
                'data': '7F'
            }
        )

    def test_054(self, name='<Transition to extendedSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='10 03',
            expected={
                'response': 'Positive',
                'dataLength': '4'
            }
        )

    def test_055(self, name='<Activate TesterPresent>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )

    def test_057(self, name='<Start Routine> Physical Address Req'):
        test.preconditions(
            step_info=info()
        )
        if device_under_test is 'MSM':
            test.step(
                step_title=name,
                custom='31 01 02 7B 02 ',
                expected={
                    'response': 'Negative',
                    'data': '33'
                }
            )
        if device_under_test == 'TCP':
            test.step(
                step_title=name,
                custom='31 01 02 C0 00',
                expected={
                    'response': 'Negative',
                    'data': '33'
                }
            )
        if device_under_test in ['PTM','ARB']:
            test.step(
                step_title=name,
                custom='31 01 03 41 00 00',
                expected={
                    'response': 'Negative',
                    'data': '33'
                }
            )
        if device_under_test is 'SCL':
            print(name, 'Test is not supported by %s'%device_under_test)

    def test_058(self, name='<Unlock Security Level 0D, ServiceProgramming>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            request_seed='0D',
            expected={
                'response'            : 'Positive',
                'dataLength'          : 31,
                'unexpected_response' : True,
                'partialData'         : ('00', 'FF')
            }
        )

    def test_059(self, name='<Unlock the Server via security access 0D service>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            send_key='0D',
            expected={
                'response': 'Positive'
            }
        )

    def test_060(self, name='<Verify Server is enforcing ECU Service Programming Routine>'):
        test.preconditions(
            step_info=info()
        )
        if device_under_test is 'MSM':
            test.step(
                step_title=name,
                custom='31 01 02 7B 02',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test is 'SCL':
            test.step(
                step_title=name,
                custom='31 01 FF 01',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test in ['ARB','TCP']:
            test.step(
                step_title=name,
                custom='31 01 02 C0 00',
                expected={
                    'response': 'Positive'
                }
            )
        if device_under_test == 'PTM':
            test.preconditions(
                step_info=info(),
                signal=['RCIP_RrClsrMtnCtlParmEnblAuth','SrlDat2_Prtctd_PDU',1]                
                ) 
            time.sleep(8)    
            test.step(
                step_title=name,
                custom='31 01 03 41 00 00',
                expected={
                    'response': 'Positive'
                }
            )

    def test_061(self, name='Send valid testerPresent, service 3E, within P3 for 2 minutes + Stop periodically transmitted TesterPresent and wait for S3 Timeout + 100 msec, 5.1 seconds, for the Session Timing parameter to timeout'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )
        tools.timer.input('Wait for 2 minutes...', timeout=120)
        test.preconditions(current_step='- Stop tester present -')
        test.step(step_title='- Stop tester present -',
                    stop_tester_present=True)
        tools.timer.input('Wait for S3 Timeout + 100ms', timeout=6)

    def test_063(self, name='<Verify return to defaultSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='28 03 01',
            expected={
                'response': 'Negative',
                'data': '7F'
            }
        )

    def test_064(self, name='<Transition to extendedSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='10 03',
            expected={
                'response': 'Positive',
                'dataLength': '4'
            }
        )

    def test_065(self, name='<Activate TesterPresent>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )

    def test_067(self, name='<Start Routine> Physical Address Req'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='31 01 02 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  55 1B AF A3 B9 5A 64 DF 9B 40 B8 FD 17 A4 74 33 E1 C9 44 E9 18 F2 20 54 B9 E6 B0 65 A8 3E 73 28 3E C4 F4 B2 F3 70 F7 43 52 FF BD B6 83 BE 82 DB 49',
            expected={
                'response': 'Negative',
                'data': '33'
            }
        )

    def test_068(self, name='<Unlock Security Level 11, ServiceProgramming>'):       
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            communication_control=False,  # updated by HC  add
            request_seed='11',
            expected={
                'response'            : 'Positive',
                'dataLength'          : 31,
                'unexpected_response' : True,
                'partialData'         : ('00', 'FF')
            }
        )

    def test_069(self, name='<Unlock the Server via security access 11 service>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            send_key='11',
            expected={
                'response': 'Positive'
            }
        )

    def test_070(self, name='<Verify Server is enforcing ECU Service Programming Routine>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='31 01 02 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  55 1B AF A3 B9 5A 64 DF 9B 40 B8 FD 17 A4 74 33 E1 C9 44 E9 18 F2 20 54 B9 E6 B0 65 A8 3E 73 28 3E C4 F4 B2 F3 70 F7 43 52 FF BD B6 83 BE 82 DB 49',
            expected={
                'response': 'Positive'
            }
        )

    def test_071(self, name='Send valid testerPresent, service 3E, within P3 for 2 minutes + Stop periodically transmitted TesterPresent and wait for S3 Timeout + 100 msec, 5.1 seconds, for the Session Timing parameter to timeout'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            start_tester_present=True,
            expected={
                'response': 'No response'
            }
        )
        tools.timer.input('Wait for 2 minutes...', timeout=120)
        test.preconditions(current_step='- Stop tester present -')
        test.step(step_title='- Stop tester present -',
                    stop_tester_present=True)
        tools.timer.input('Wait for S3 Timeout + 100ms', timeout=6)

    def test_073(self, name='<Verify return to defaultSession>'):
        test.preconditions(
            step_info=info()
        )
        test.step(
            step_title=name,
            custom='28 03 01',
            expected={
                'response': 'Negative',
                'data': '7F'
            }
        )
        test.restart_communication()

    def test_074(self, name='Pyrotechnic ECU Test'):
        pass

    def test_075(self, name='Pyrotechnic ECU Test'):
        pass

    def test_077(self, name='Pyrotechnic ECU Test'):
        pass

    def test_078(self, name='Pyrotechnic ECU Test'):
        pass

    def test_079(self, name='Pyrotechnic ECU Test'):
        pass

    def test_080(self, name='Pyrotechnic ECU Test'):
        pass

    def test_081(self, name='Pyrotechnic ECU Test'):
        pass

    def test_083(self, name='Pyrotechnic ECU Test'):
        pass


